version: "3.8"
services:
  api:
    env_file: ./configs/api.env
    volumes:
      - ./api/src:/home/app/src
  worker:
    env_file: ./configs/worker.env
    volumes:
      - ./worker/src:/home/app/src
